//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public System.DateTime ID { get; set; }
        public string MaNV { get; set; }
        public string MaCa { get; set; }
        public string MaKV { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        public virtual PhanCong PhanCong { get; set; }
    }
}
