//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuVuc
    {
        public KhuVuc()
        {
            this.Bans = new HashSet<Ban>();
            this.PhanCongs = new HashSet<PhanCong>();
        }
    
        public string MaKV { get; set; }
        public string TenKV { get; set; }
    
        public virtual ICollection<Ban> Bans { get; set; }
        public virtual ICollection<PhanCong> PhanCongs { get; set; }
    }
}
