//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.PhanCongs = new HashSet<PhanCong>();
            this.PhieuChis = new HashSet<PhieuChi>();
        }
    
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> Phai { get; set; }
        public string CMND { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public string MatKhau { get; set; }
        public Nullable<bool> Quyen { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual ICollection<PhanCong> PhanCongs { get; set; }
        public virtual ICollection<PhieuChi> PhieuChis { get; set; }
    }
}
