//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuChi
    {
        public string MaPhieuChi { get; set; }
        public string MaNV { get; set; }
        public string MucDichChi { get; set; }
        public Nullable<System.DateTime> NgayChi { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
