//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ThongKeMonTheoNgay
    {
        public string Ngay { get; set; }
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<double> DoanhThu { get; set; }
    }
}
