//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ThongKeDoanhThu
    {
        public string MaHD { get; set; }
        public Nullable<System.DateTime> NgayLapHD { get; set; }
        public Nullable<double> PhuThu { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> TriGiaHD { get; set; }
    }
}
